# Generated by Django 3.1.7 on 2021-05-17 02:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=11)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=5)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantidade', models.IntegerField()),
                ('item_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.categoria')),
                ('item_filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.filial')),
                ('item_fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.fornecedor')),
            ],
        ),
    ]
