# Generated by Django 3.1.7 on 2021-06-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacoes',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
