# Generated by Django 3.1.7 on 2021-06-08 00:25

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_movimentacoes_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
