# Generated by Django 3.1.7 on 2021-06-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210607_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacoes',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='movimentacoes',
            name='mov_quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
