# Generated by Django 3.1.7 on 2021-06-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210608_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='movimentacoes',
            name='mov_quantidade',
        ),
    ]
